# Generated by Django 2.2.5 on 2019-12-16 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AddincomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.DateModel')),
            ],
        ),
        migrations.CreateModel(
            name='AddexpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.DateModel')),
            ],
        ),
    ]
