# Generated by Django 2.2.5 on 2019-12-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20191216_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='addexpensemodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addincomemodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datemodel',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
